import type { WidgetDefinition } from '../types/widget';
import { defaultCustomerPortalTheme, defaultPricingTableTheme } from '../data/default-theme';
import { CUSTOMER_PORTAL_ICON, PRICING_TABLE_ICON } from '../components/playground/playground-icons';

export const widgetCatalog: WidgetDefinition[] = [
  {
    id: 'customer-portal',
    name: 'Customer Portal',
    description: 'Self-serve portal for subscriptions, invoices, payment methods, and billing history.',
    status: 'Live',
    docsUrl: 'https://docs.metrifox.com/sdks/frontend/angular',
    highlights: [''],
    defaultTheme: defaultCustomerPortalTheme,
    themeScope: 'customerPortal',
    sectionDescriptions: {
      general: 'Global styles: links, background, border radius, font, and container padding.',
      tabs: 'Tab bar appearance and active/inactive tab colors.',
      sections: 'Section containers, usage bars, content blocks, and typography.',
      buttons: 'Primary and secondary button styles.',
      lineItems: 'Line item rows (parent and child) and their text colors.',
      tables: 'Data table header, rows, borders, and cell styling.',
      modals: 'Modal overlay, panel, close button, and footer buttons.',
      plans: 'Plan cards, current plan highlight, features, toggle, and tags (e.g. free trial).',
    },
    iconSvg: CUSTOMER_PORTAL_ICON,
    configs: [
      { key: 'clientKey', label: 'Client Key', type: 'text', defaultValue: 'tPVJP9Sw87rO4OWMpDtXDRzjDH1iw4bh_uShZqh1xUU', placeholder: 'Enter your client key', section: 'api' },
      { key: 'customerKey', label: 'Customer Key', type: 'text', defaultValue: 'cust-mkpo1rd3u91j', placeholder: 'Enter your customer key', section: 'api' },
      { key: 'theme.customerPortal.linkColor', label: 'Link Color', type: 'color', defaultValue: '#2563eb', section: 'Theme: General' },
      { key: 'theme.customerPortal.tabs.background', label: 'Tab Background', type: 'color', defaultValue: '#ffffff', section: 'Theme: Tabs' },
      { key: 'theme.customerPortal.tabs.borderColor', label: 'Tab Border Color', type: 'color', defaultValue: '#e5e7eb', section: 'Theme: Tabs' },
      { key: 'theme.customerPortal.tabs.activeBackground', label: 'Active Tab Background', type: 'color', defaultValue: '#eff6ff', section: 'Theme: Tabs' },
      { key: 'theme.customerPortal.tabs.activeTextColor', label: 'Active Tab Text', type: 'color', defaultValue: '#2563eb', section: 'Theme: Tabs' },
      { key: 'theme.customerPortal.tabs.inactiveTextColor', label: 'Inactive Tab Text', type: 'color', defaultValue: '#6b7280', section: 'Theme: Tabs' },
      { key: 'theme.customerPortal.section.background', label: 'Section Background', type: 'color', defaultValue: '#f1eaea', section: 'Theme: Section' },
      { key: 'theme.customerPortal.section.titleTextColor', label: 'Section Title Color', type: 'color', defaultValue: '#111827', section: 'Theme: Section' },
      { key: 'theme.customerPortal.section.contentBackground', label: 'Section Content Background', type: 'color', defaultValue: '#ffffff', section: 'Theme: Section' },
      { key: 'theme.customerPortal.section.iconBackground', label: 'Section Icon Background', type: 'color', defaultValue: '#f3f4f6', section: 'Theme: Section' },
      { key: 'theme.customerPortal.section.iconColor', label: 'Section Icon Color', type: 'color', defaultValue: '#4b5563', section: 'Theme: Section' },
      { key: 'theme.customerPortal.section.emptyTextColor', label: 'Section Empty Text', type: 'color', defaultValue: '#6b7280', section: 'Theme: Section' },
      { key: 'theme.customerPortal.card.titleBackground', label: 'Card Title Background', type: 'color', defaultValue: '#f9fafb', section: 'Theme: Card' },
      { key: 'theme.customerPortal.card.contentBackground', label: 'Card Content Background', type: 'color', defaultValue: '#ffffff', section: 'Theme: Card' },
      { key: 'theme.customerPortal.card.titleColor', label: 'Card Title Color', type: 'color', defaultValue: '#111827', section: 'Theme: Card' },
      { key: 'theme.customerPortal.card.details.labelColor', label: 'Card Label Color', type: 'color', defaultValue: '#6b7280', section: 'Theme: Card' },
      { key: 'theme.customerPortal.card.details.valueColor', label: 'Card Value Color', type: 'color', defaultValue: '#111827', section: 'Theme: Card' },
      { key: 'theme.customerPortal.subscription.items.background', label: 'Subscription Item Background', type: 'color', defaultValue: '#ffffff', section: 'Theme: Subscription' },
      { key: 'theme.customerPortal.subscription.items.borderColor', label: 'Subscription Item Border Color', type: 'color', defaultValue: '#e5e7eb', section: 'Theme: Subscription' },
      { key: 'theme.customerPortal.subscription.items.textColor', label: 'Subscription Item Text', type: 'color', defaultValue: '#111827', section: 'Theme: Subscription' },
      { key: 'theme.customerPortal.table.headerTextColor', label: 'Table Header Text', type: 'color', defaultValue: '#6b7280', section: 'Theme: Table' },
      { key: 'theme.customerPortal.table.textColor', label: 'Table Text Color', type: 'color', defaultValue: '#111827', section: 'Theme: Table' },
      { key: 'theme.customerPortal.button.background', label: 'Button Background', type: 'color', defaultValue: '#2563eb', section: 'Theme: Button' },
      { key: 'theme.customerPortal.button.textColor', label: 'Button Text Color', type: 'color', defaultValue: '#ffffff', section: 'Theme: Button' },
      { key: 'theme.customerPortal.filter.border', label: 'Filter Border', type: 'color', defaultValue: '#e5e7eb', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.filter.activeBackground', label: 'Filter Active Background', type: 'color', defaultValue: '#eff6ff', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.filter.inactiveBackground', label: 'Filter Inactive Background', type: 'color', defaultValue: '#ffffff', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.filter.activeTextColor', label: 'Filter Active Text', type: 'color', defaultValue: '#2563eb', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.filter.inactiveTextColor', label: 'Filter Inactive Text', type: 'color', defaultValue: '#6b7280', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.filter.countBackground', label: 'Filter Count Background', type: 'color', defaultValue: '#dbeafe', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.filter.countTextColor', label: 'Filter Count Text', type: 'color', defaultValue: '#1e40af', section: 'Theme: Filter' },
      { key: 'theme.customerPortal.plan.card.background', label: 'Card Background', type: 'color', defaultValue: '#ffffff', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.borderColor', label: 'Card Border Color', type: 'color', defaultValue: '#e5e7eb', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.descriptionColor', label: 'Description Color', type: 'color', defaultValue: '#374151', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.header.background', label: 'Header Background', type: 'color', defaultValue: '#f9fafb', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.header.textColor', label: 'Header Text Color', type: 'color', defaultValue: '#111827', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.description.textColor', label: 'Description Text Color', type: 'color', defaultValue: '#6b7280', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.description.textButtonColor', label: 'Description Button Color', type: 'color', defaultValue: '#2563eb', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.price.amountColor', label: 'Price Amount Color', type: 'color', defaultValue: '#111827', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.price.primaryTextColor', label: 'Price Primary Text', type: 'color', defaultValue: '#6b7280', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.price.secondaryTextColor', label: 'Price Secondary Text', type: 'color', defaultValue: '#9ca3af', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.price.background', label: 'Price Background', type: 'color', defaultValue: 'transparent', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.card.price.borderColor', label: 'Price Border Color', type: 'color', defaultValue: 'transparent', section: 'Theme: Plan Card' },
      { key: 'theme.customerPortal.plan.currentSubscriptionCard.header.background', label: 'Subscription Header Background', type: 'color', defaultValue: '#f3f4f6', section: 'Theme: Current Subscription' },
      { key: 'theme.customerPortal.plan.currentSubscriptionCard.header.textColor', label: 'Subscription Header Text', type: 'color', defaultValue: '#111827', section: 'Theme: Current Subscription' },
      { key: 'theme.customerPortal.plan.currentSubscriptionCard.gradientColor', label: 'Subscription Gradient', type: 'color', defaultValue: '#e5e7eb', section: 'Theme: Current Subscription' },
      { key: 'theme.customerPortal.plan.featureList.textColor', label: 'Feature Text Color', type: 'color', defaultValue: '#374151', section: 'Theme: Plan Features' },
      { key: 'theme.customerPortal.plan.featureList.iconColor', label: 'Feature Icon Color', type: 'color', defaultValue: '#2563eb', section: 'Theme: Plan Features' },
      { key: 'theme.customerPortal.plan.button.background', label: 'Button Background', type: 'color', defaultValue: '#2563eb', section: 'Theme: Plan Button' },
      { key: 'theme.customerPortal.plan.button.textColor', label: 'Button Text Color', type: 'color', defaultValue: '#ffffff', section: 'Theme: Plan Button' },
      { key: 'theme.customerPortal.plan.intervalToggle.background', label: 'Toggle Background', type: 'color', defaultValue: '#e5e7eb', section: 'Theme: Plan Toggle' },
      { key: 'theme.customerPortal.plan.intervalToggle.activeBackground', label: 'Active Toggle Background', type: 'color', defaultValue: '#1f2937', section: 'Theme: Plan Toggle' },
      { key: 'theme.customerPortal.plan.intervalToggle.activeText', label: 'Active Toggle Text', type: 'color', defaultValue: '#ffffff', section: 'Theme: Plan Toggle' },
      { key: 'theme.customerPortal.plan.freeTrialTag.background', label: 'Free Trial Background', type: 'color', defaultValue: '#dbeafe', section: 'Theme: Plan Tags' },
      { key: 'theme.customerPortal.plan.freeTrialTag.textColor', label: 'Free Trial Text', type: 'color', defaultValue: '#1e40af', section: 'Theme: Plan Tags' },
    ],
  },
  {
    id: 'pricing-table',
    name: 'Pricing cards',
    description: 'Composable pricing surfaces that update in real time across touchpoints.',
    status: 'Live',
    docsUrl: 'https://docs.metrifox.com/sdks/frontend/angular',
    highlights: [''],
    defaultTheme: defaultPricingTableTheme,
    themeScope: 'pricingTable',
    sectionDescriptions: {
      display: 'Control which content and tabs are shown (plans only, one-time purchases, tab header).',
      card: 'Card container, header, description, and price block colors.',
      button: 'Primary and secondary CTA button colors.',
      featureList: 'Feature list text and icon colors.',
      tabs: 'Plan vs one-time tab styling.',
      intervalToggle: 'Billing interval toggle (e.g. monthly/yearly) colors.',
    },
    iconSvg: PRICING_TABLE_ICON,
    configs: [
      { key: 'clientKey', label: 'Client Key', type: 'text', defaultValue: 'tPVJP9Sw87rO4OWMpDtXDRzjDH1iw4bh_uShZqh1xUU', section: 'api' },
      { key: 'checkoutKey', label: 'Checkout Username', type: 'text', defaultValue: 'sandbox-adedapo-s-inc', section: 'api' },
      { key: 'productKey', label: 'Product Key', type: 'text', defaultValue: 'product_metrifox_billing_product_fc6c', section: 'api' },
    ],
  },
];
